version: '3.7'
services:

  #PHP Service
  app-semec:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app-semec
    restart: unless-stopped
    tty: true
    ports:
      - "9001:9000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/sm-semec
    volumes:
      - ./:/var/www/sm-semec
      - ./shared/php/server.ini:/usr/local/etc/php/conf.d/server.ini
      - vendor_path:/vendor
    networks:
      - app-network
    depends_on:
      - db-semec

  #MySQL Service
  db-semec:
    image: mysql:5.7.22
    container_name: db-semec
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: sm_semec
      MYSQL_USER: sm-semec
      MYSQL_PASSWORD: sm-semec
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./shared/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  vendor_path:
